### ISSUE TITLE
need some more info

### ISSUE THREAD

**Issue by paqpaqpaq** [malosaa/PostNL_DHL_Tracker_HA#2]
I implemented your code. Two things though :)

1. Will the lovelace card show only 1 parcel at a time? In other words: 3 parcels in 1 view would not be possible?
2. I have no output on a valid tracking number:

<img width="367" alt="Scherm­afbeelding 2023-10-30 om 13 31 57" src="https://github.com/malosaa/PostNL_DHL_Tracker_HA/assets/34166264/6b90120e-c856-48e6-8e99-0805eefd4ddc">

**Comment by EvertJob** [comment]
The URL in `sensor.postnl_rest_resource` shows a valid output but it's not saved to the sensor itself

**Comment by Tosko4** [comment]
@EvertJob  and @paqpaqpaq 

rest should be as followed, attribute **colli** is missing

```
rest:
  - authentication: basic
    resource_template: "{{ states('sensor.postNL_rest_resource') }}"
    scan_interval: 80000
    sensor:
      - name: postnl_tracker
        unique_id: 854729072388394756
        value_template: 'ok'
        json_attributes:
          - "processed"
          - "colli"
```
