### ISSUE TITLE
Issue with tracking

### ISSUE THREAD

**Issue by Fabian-Ser** [malosaa/PostNL_DHL_Tracker_HA#3]
I added the configuration to my configuration.yml (https://github.com/malosaa/PostNL_DHL_Tracker_HA/blob/main/config/packages/rest/post_nl_tracker.yaml) and added the helpers. In the helpers I did add my postal code and tracking code and added the entities to my dashboard. Now my "Delivery time", "Identification", "Recipient", "Sender" is "not available".

When I inspect the raw data of "postnl_tracker" it shows all the correct data, also the "PostNL REST Resource" contains a valid URL with all the correct data.

Am I doing something wrong?

![image](https://github.com/malosaa/PostNL_DHL_Tracker_HA/assets/25509772/5d11bb3d-9b83-4098-a473-600c9554e994)
![image](https://github.com/malosaa/PostNL_DHL_Tracker_HA/assets/25509772/ec522984-19d0-4118-8ffa-13c0d2410f43)

Thanks!

**Comment by malosaa** [comment]
Hi,

Can you show me your configuration?
as for me it still works normal.


what happens if u go to DEVELOPER TOOLS > TEMPLATE paste this in there:

```{{ state_attr('sensor.postnl_tracker', 'colli')[tracking_code]['recipient']['names']['personName'] }}```


Also be sure the data is available in your REST sensor, just double check it.
```
rest:
  - authentication: basic
    resource_template: "{{ states('sensor.postNL_rest_resource') }}"
    scan_interval: 80000
    sensor:
    - name: postnl_tracker
      unique_id: 854729072388394756
      value_template: 'ok'
      json_attributes:
        - "processed" 
        - "colli"
```        
Here is my full config

https://github.com/malosaa/PostNL_DHL_Tracker_HA/blob/main/config/packages/rest/post_nl_tracker.yaml

Or there has been a typo in the lovelace code, be sure you doublecheck that too.
The code is also available in my repo.


regards
